export const options = [
  {
    id: 0,
    que: "My child seems to enjoy entertaining themselves for long periods of time.",
    name: "question1",
    option: [
      { id: 0, answer: "2E" },
      { id: 1, answer: "1E" },
      { id: 2, answer: "1I" },
      { id: 3, answer: "2I" },
    ],
  },
  {
    id: 1,
    que: "Seeing someone else cry or get hurt would make my child cry as well.",
    name: "question2",
    option: [
      { id: 0, answer: "2T" },
      { id: 1, answer: "1T" },
      { id: 2, answer: "1F" },
      { id: 3, answer: "2F" },
    ],
  },
  {
    id: 2,
    que: "My child is great at planning ahead and being efficient.",
    name: "question1",
    option: [
      { id: 0, answer: "2P" },
      { id: 1, answer: "1P" },
      { id: 2, answer: "1J" },
      { id: 3, answer: "2J" },
    ],
  },
  {
    id: 3,
    que: "My child can usually stay calm, even under a lot of pressure.",
    name: "question1",
    option: [
      { id: 0, answer: "2F" },
      { id: 1, answer: "1F" },
      { id: 2, answer: "1T" },
      { id: 3, answer: "2T" },
    ],
  },
  {
    id: 4,
    que: "At social events, my child has no problem striking up a conversation with someone.",
    name: "question1",
    option: [
      { id: 0, answer: "2I" },
      { id: 1, answer: "1I" },
      { id: 2, answer: "1E" },
      { id: 3, answer: "2E" },
    ],
  },
  {
    id: 5,
    que: "My child seems to want to fully complete a project or task before moving to the next one.",
    name: "question1",
    option: [
      { id: 0, answer: "2P" },
      { id: 1, answer: "1P" },
      { id: 2, answer: "1J" },
      { id: 3, answer: "2J" },
    ],
  },
  {
    id: 6,
    que: "My child is more inclined to follow their head rather than their heart.",
    name: "question1",
    option: [
      { id: 0, answer: "2F" },
      { id: 1, answer: "1F" },
      { id: 2, answer: "1T" },
      { id: 3, answer: "2T" },
    ],
  },
  {
    id: 7,
    que: "When reading a story, my child seems to remember specific details about that story rather than any themes.",
    name: "question1",
    option: [
      { id: 0, answer: "2N" },
      { id: 1, answer: "1N" },
      { id: 2, answer: "1S" },
      { id: 3, answer: "2S" },
    ],
  },
  {
    id: 8,
    que: "My child would speak their mind honestly, even if it would hurt the feelings of someone else.",
    name: "question1",
    option: [
      { id: 0, answer: "2F" },
      { id: 1, answer: "1F" },
      { id: 2, answer: "1T" },
      { id: 3, answer: "2T" },
    ],
  },
  {
    id: 9,
    que: "My child likes to explore and go with the flow.",
    name: "question1",
    option: [
      { id: 0, answer: "2J" },
      { id: 1, answer: "1J" },
      { id: 2, answer: "1P" },
      { id: 3, answer: "2P" },
    ],
  },
  {
    id: 10,
    que: "My child would rather put their ideas into action rather than just think about creative ideas.",
    name: "question1",
    option: [
      { id: 0, answer: "2N" },
      { id: 1, answer: "1N" },
      { id: 2, answer: "1S" },
      { id: 3, answer: "2S" },
    ],
  },
  {
    id: 11,
    que: "If given a to-do list, my child would most likely bounce around the list to what they are interested in, rather than doing the list in order.",
    name: "question1",
    option: [
      { id: 0, answer: "2J" },
      { id: 1, answer: "1J" },
      { id: 2, answer: "1P" },
      { id: 3, answer: "2P" },
    ],
  },
  {
    id: 12,
    que: "My child would rather have a fair and clear teacher that is more cold, than an inconsistent teacher that is loving and warm.",
    name: "question1",
    option: [
      { id: 0, answer: "2F" },
      { id: 1, answer: "1F" },
      { id: 2, answer: "1T" },
      { id: 3, answer: "2T" },
    ],
  },
  {
    id: 13,
    que: "My child does work right away and does not wait until the last minute. They don’t have a problem with deadlines.",
    name: "question1",
    option: [
      { id: 0, answer: "2P" },
      { id: 1, answer: "1P" },
      { id: 2, answer: "1J" },
      { id: 3, answer: "2J" },
    ],
  },
  {
    id: 14,
    que: "My child prefers to play in groups and seems to get energized by it.",
    name: "question1",
    option: [
      { id: 0, answer: "2I" },
      { id: 1, answer: "1I" },
      { id: 2, answer: "1E" },
      { id: 3, answer: "2E" },
    ],
  },
];
